/**
 * Auto-generated migration index
 * Generated at: 2025-08-09T07:20:05.909Z
 *
 * This file is automatically generated from classification.json
 * To update this file, modify classification.json and run:
 * node .claude/data-classify/scripts/generate-migration.js
 *
 * === AUTO-GENERATED CONTENT START ===
 */

// LEGACY MIGRATION SYSTEM - COMMENTED OUT
// These files have been replaced by PreferencesMigrator.ts
// import { ElectronStoreMigrator } from './electronStoreToPreferences'
// import { ReduxMigrator } from './reduxToPreferences'
import { loggerService } from '@logger'

const logger = loggerService.withContext('MigrationManager')

export interface MigrationResult {
  success: boolean
  migratedCount: number
  errors: Array<{
    key: string
    error: string
  }>
  source: 'electronStore' | 'redux'
}

export interface MigrationSummary {
  totalItems: number
  successCount: number
  errorCount: number
  electronStore: MigrationResult
  redux: MigrationResult
}

export class MigrationManager {
  // LEGACY MIGRATION SYSTEM - COMMENTED OUT
  // private electronStoreMigrator: ElectronStoreMigrator
  // private reduxMigrator: ReduxMigrator

  constructor() {
    // this.electronStoreMigrator = new ElectronStoreMigrator()
    // this.reduxMigrator = new ReduxMigrator()
    logger.warn('MigrationManager is deprecated. Use PreferencesMigrator instead.')
  }

  /**
   * 执行完整的preferences迁移
   * @returns 迁移摘要
   */
  async migrateAllPreferences(): Promise<MigrationSummary> {
    logger.warn('MigrationManager.migrateAllPreferences is deprecated. Use PreferencesMigrator instead.')

    // Return a placeholder summary since the actual migration is handled by PreferencesMigrator
    const summary: MigrationSummary = {
      totalItems: 0,
      successCount: 0,
      errorCount: 0,
      electronStore: { success: false, migratedCount: 0, errors: [], source: 'electronStore' },
      redux: { success: false, migratedCount: 0, errors: [], source: 'redux' }
    }

    return summary
  }

  /**
   * 验证迁移结果
   * @param summary 迁移摘要
   * @returns 是否验证成功
   */
  async validateMigration(_summary: MigrationSummary): Promise<boolean> {
    logger.warn('MigrationManager.validateMigration is deprecated. Use PreferencesMigrator validation instead.')
    return true
  }
}

// === AUTO-GENERATED CONTENT END ===

/**
 * 生成统计:
 * - 总迁移项: 158
 * - ElectronStore项: 4
 * - Redux项: 154
 */
