import { defaultActionItems } from './pending_default_values'
import type { SelectionActionItem, SelectionFilterMode, SelectionTriggerMode } from './types'

/**
 * Auto-generated preferences configuration
 * Generated at: 2025-08-15T03:23:46.568Z
 *
 * This file is automatically generated from classification.json
 * To update this file, modify classification.json and run:
 * node .claude/data-classify/scripts/generate-preferences.js
 *
 * === AUTO-GENERATED CONTENT START ===
 */

/* eslint @typescript-eslint/member-ordering: ["error", {
  "interfaces": { "order": "alphabetically" },
  "typeLiterals": { "order": "alphabetically" }
}] */
export interface PreferencesType {
  default: {
    // redux/settings/enableDeveloperMode
    'app.developer_mode.enabled': boolean
    // redux/settings/disableHardwareAcceleration
    'app.disable_hardware_acceleration': boolean
    // redux/settings/autoCheckUpdate
    'app.dist.auto_update.enabled': boolean
    // redux/settings/testChannel
    'app.dist.test_plan.channel': string
    // redux/settings/testPlan
    'app.dist.test_plan.enabled': boolean
    // electronStore/Language/Language
    'app.language': string | null
    // redux/settings/launchOnBoot
    'app.launch_on_boot': boolean
    // redux/settings/notification.assistant
    'app.notification.assistant.enabled': boolean
    // redux/settings/notification.backup
    'app.notification.backup.enabled': boolean
    // redux/settings/notification.knowledge
    'app.notification.knowledge.enabled': boolean
    // redux/settings/enableDataCollection
    'app.privacy.data_collection.enabled': boolean
    // redux/settings/proxyBypassRules
    'app.proxy.bypass_rules': string | null
    // redux/settings/proxyMode
    'app.proxy.mode': string
    // redux/settings/proxyUrl
    'app.proxy.url': string | null
    // redux/settings/enableSpellCheck
    'app.spell_check.enabled': boolean
    // redux/settings/spellCheckLanguages
    'app.spell_check.languages': unknown[]
    // redux/settings/theme
    'app.theme.mode': string
    // redux/settings/userTheme
    'app.theme.user_defined': Record<string, unknown>
    // redux/settings/windowStyle
    'app.theme.window_style': string
    // redux/settings/tray
    'app.tray.enabled': boolean
    // redux/settings/trayOnClose
    'app.tray.on_close': boolean
    // redux/settings/launchToTray
    'app.tray.on_launch': boolean
    // redux/settings/userId
    'app.user.id': string
    // redux/settings/userName
    'app.user.name': string
    // electronStore/ZoomFactor/ZoomFactor
    'app.zoom_factor': number
    // redux/settings/codeCollapsible
    'chat.code.collapsible': boolean
    // redux/settings/codeEditor.autocompletion
    'chat.code.editor.autocompletion': boolean
    // redux/settings/codeEditor.foldGutter
    'chat.code.editor.fold_gutter': boolean
    // redux/settings/codeEditor.enabled
    'chat.code.editor.highlight_active_line': boolean
    // redux/settings/codeEditor.keymap
    'chat.code.editor.keymap': boolean
    // redux/settings/codeEditor.themeDark
    'chat.code.editor.theme_dark': string
    // redux/settings/codeEditor.themeLight
    'chat.code.editor.theme_light': string
    // redux/settings/codeExecution.enabled
    'chat.code.execution.enabled': boolean
    // redux/settings/codeExecution.timeoutMinutes
    'chat.code.execution.timeout_minutes': number
    // redux/settings/codeImageTools
    'chat.code.image_tools': boolean
    // redux/settings/codePreview.themeDark
    'chat.code.preview.theme_dark': string
    // redux/settings/codePreview.themeLight
    'chat.code.preview.theme_light': string
    // redux/settings/codeShowLineNumbers
    'chat.code.show_line_numbers': boolean
    // redux/settings/codeViewer.themeDark
    'chat.code.viewer.theme_dark': string
    // redux/settings/codeViewer.themeLight
    'chat.code.viewer.theme_light': string
    // redux/settings/codeWrappable
    'chat.code.wrappable': boolean
    // redux/settings/enableBackspaceDeleteModel
    'chat.input.backspace_delete_model': boolean
    // redux/settings/pasteLongTextAsFile
    'chat.input.paste_long_text_as_file': boolean
    // redux/settings/pasteLongTextThreshold
    'chat.input.paste_long_text_threshold': number
    // redux/settings/enableQuickPanelTriggers
    'chat.input.quick_panel.triggers_enabled': boolean
    // redux/settings/sendMessageShortcut
    'chat.input.send_message_shortcut': string
    // redux/settings/showInputEstimatedTokens
    'chat.input.show_estimated_tokens': boolean
    // redux/settings/autoTranslateWithSpace
    'chat.input.translate.auto_translate_with_space': boolean
    // redux/settings/showTranslateConfirm
    'chat.input.translate.show_confirm': boolean
    // redux/settings/messageFont
    'chat.message.font': string
    // redux/settings/fontSize
    'chat.message.font_size': number
    // redux/settings/mathEngine
    'chat.message.math_engine': string
    // redux/settings/foldDisplayMode
    'chat.message.multi_model.fold_display_mode': string
    // redux/settings/gridColumns
    'chat.message.multi_model.grid_columns': number
    // redux/settings/gridPopoverTrigger
    'chat.message.multi_model.grid_popover_trigger': string
    // redux/settings/multiModelMessageStyle
    'chat.message.multi_model.style': string
    // redux/settings/messageNavigation
    'chat.message.navigation_mode': string
    // redux/settings/showMessageDivider
    'chat.message.show_divider': boolean
    // redux/settings/showPrompt
    'chat.message.show_prompt': boolean
    // redux/settings/showTokens
    'chat.message.show_tokens': boolean
    // redux/settings/messageStyle
    'chat.message.style': string
    // redux/settings/thoughtAutoCollapse
    'chat.message.thought.auto_collapse': boolean
    // redux/settings/narrowMode
    'chat.narrow_mode': boolean
    // redux/settings/skipBackupFile
    'data.backup.general.skip_backup_file': boolean
    // redux/settings/localBackupAutoSync
    'data.backup.local.auto_sync': boolean
    // redux/settings/localBackupDir
    'data.backup.local.dir': string
    // redux/settings/localBackupMaxBackups
    'data.backup.local.max_backups': number
    // redux/settings/localBackupSkipBackupFile
    'data.backup.local.skip_backup_file': boolean
    // redux/settings/localBackupSyncInterval
    'data.backup.local.sync_interval': number
    // redux/nutstore/nutstoreAutoSync
    'data.backup.nutstore.auto_sync': boolean | null
    // redux/nutstore/nutstorePath
    'data.backup.nutstore.path': string | null
    // redux/nutstore/nutstoreSkipBackupFile
    'data.backup.nutstore.skip_backup_file': boolean | null
    // redux/nutstore/nutstoreSyncInterval
    'data.backup.nutstore.sync_interval': number | null
    // redux/nutstore/nutstoreSyncState
    'data.backup.nutstore.sync_state': Record<string, unknown> | null
    // redux/nutstore/nutstoreToken
    'data.backup.nutstore.token': string | null
    // redux/settings/s3.accessKeyId
    'data.backup.s3.access_key_id': string
    // redux/settings/s3.autoSync
    'data.backup.s3.auto_sync': boolean
    // redux/settings/s3.bucket
    'data.backup.s3.bucket': string
    // redux/settings/s3.endpoint
    'data.backup.s3.endpoint': string
    // redux/settings/s3.maxBackups
    'data.backup.s3.max_backups': number
    // redux/settings/s3.region
    'data.backup.s3.region': string
    // redux/settings/s3.root
    'data.backup.s3.root': string
    // redux/settings/s3.secretAccessKey
    'data.backup.s3.secret_access_key': string
    // redux/settings/s3.skipBackupFile
    'data.backup.s3.skip_backup_file': boolean
    // redux/settings/s3.syncInterval
    'data.backup.s3.sync_interval': number
    // redux/settings/webdavAutoSync
    'data.backup.webdav.auto_sync': boolean
    // redux/settings/webdavDisableStream
    'data.backup.webdav.disable_stream': boolean
    // redux/settings/webdavHost
    'data.backup.webdav.host': string
    // redux/settings/webdavMaxBackups
    'data.backup.webdav.max_backups': number
    // redux/settings/webdavPass
    'data.backup.webdav.pass': string
    // redux/settings/webdavPath
    'data.backup.webdav.path': string
    // redux/settings/webdavSkipBackupFile
    'data.backup.webdav.skip_backup_file': boolean
    // redux/settings/webdavSyncInterval
    'data.backup.webdav.sync_interval': number
    // redux/settings/webdavUser
    'data.backup.webdav.user': string
    // redux/settings/excludeCitationsInExport
    'data.export.markdown.exclude_citations': boolean
    // redux/settings/forceDollarMathInMarkdown
    'data.export.markdown.force_dollar_math': boolean
    // redux/settings/markdownExportPath
    'data.export.markdown.path': string | null
    // redux/settings/showModelNameInMarkdown
    'data.export.markdown.show_model_name': boolean
    // redux/settings/showModelProviderInMarkdown
    'data.export.markdown.show_model_provider': boolean
    // redux/settings/standardizeCitationsInExport
    'data.export.markdown.standardize_citations': boolean
    // redux/settings/useTopicNamingForMessageTitle
    'data.export.markdown.use_topic_naming_for_message_title': boolean
    // redux/settings/exportMenuOptions.docx
    'data.export.menus.docx': boolean
    // redux/settings/exportMenuOptions.image
    'data.export.menus.image': boolean
    // redux/settings/exportMenuOptions.joplin
    'data.export.menus.joplin': boolean
    // redux/settings/exportMenuOptions.markdown
    'data.export.menus.markdown': boolean
    // redux/settings/exportMenuOptions.markdown_reason
    'data.export.menus.markdown_reason': boolean
    // redux/settings/exportMenuOptions.notion
    'data.export.menus.notion': boolean
    // redux/settings/exportMenuOptions.obsidian
    'data.export.menus.obsidian': boolean
    // redux/settings/exportMenuOptions.plain_text
    'data.export.menus.plain_text': boolean
    // redux/settings/exportMenuOptions.siyuan
    'data.export.menus.siyuan': boolean
    // redux/settings/exportMenuOptions.yuque
    'data.export.menus.yuque': boolean
    // redux/settings/joplinExportReasoning
    'data.integration.joplin.export_reasoning': boolean
    // redux/settings/joplinToken
    'data.integration.joplin.token': string
    // redux/settings/joplinUrl
    'data.integration.joplin.url': string
    // redux/settings/notionApiKey
    'data.integration.notion.api_key': string
    // redux/settings/notionDatabaseID
    'data.integration.notion.database_id': string
    // redux/settings/notionExportReasoning
    'data.integration.notion.export_reasoning': boolean
    // redux/settings/notionPageNameKey
    'data.integration.notion.page_name_key': string
    // redux/settings/defaultObsidianVault
    'data.integration.obsidian.default_vault': string | null
    // redux/settings/siyuanApiUrl
    'data.integration.siyuan.api_url': string | null
    // redux/settings/siyuanBoxId
    'data.integration.siyuan.box_id': string | null
    // redux/settings/siyuanRootPath
    'data.integration.siyuan.root_path': string | null
    // redux/settings/siyuanToken
    'data.integration.siyuan.token': string | null
    // redux/settings/yuqueRepoId
    'data.integration.yuque.repo_id': string
    // redux/settings/yuqueToken
    'data.integration.yuque.token': string
    // redux/settings/yuqueUrl
    'data.integration.yuque.url': string
    // redux/settings/apiServer.apiKey
    'feature.csaas.api_key': string
    // redux/settings/apiServer.enabled
    'feature.csaas.enabled': boolean
    // redux/settings/apiServer.host
    'feature.csaas.host': string
    // redux/settings/apiServer.port
    'feature.csaas.port': number
    // redux/settings/maxKeepAliveMinapps
    'feature.minapp.max_keep_alive': number
    // redux/settings/minappsOpenLinkExternal
    'feature.minapp.open_link_external': boolean
    // redux/settings/showOpenedMinappsInSidebar
    'feature.minapp.show_opened_in_sidebar': boolean
    // redux/settings/clickTrayToShowQuickAssistant
    'feature.quick_assistant.click_tray_to_show': boolean
    // redux/settings/enableQuickAssistant
    'feature.quick_assistant.enabled': boolean
    // redux/settings/readClipboardAtStartup
    'feature.quick_assistant.read_clipboard_at_startup': boolean
    // redux/selectionStore/actionItems
    'feature.selection.action_items': SelectionActionItem[]
    // redux/selectionStore/actionWindowOpacity
    'feature.selection.action_window_opacity': number
    // redux/selectionStore/isAutoClose
    'feature.selection.auto_close': boolean
    // redux/selectionStore/isAutoPin
    'feature.selection.auto_pin': boolean
    // redux/selectionStore/isCompact
    'feature.selection.compact': boolean
    // redux/selectionStore/selectionEnabled
    'feature.selection.enabled': boolean
    // redux/selectionStore/filterList
    'feature.selection.filter_list': string[]
    // redux/selectionStore/filterMode
    'feature.selection.filter_mode': SelectionFilterMode
    // redux/selectionStore/isFollowToolbar
    'feature.selection.follow_toolbar': boolean
    // redux/selectionStore/isRemeberWinSize
    'feature.selection.remember_win_size': boolean
    // redux/selectionStore/triggerMode
    'feature.selection.trigger_mode': SelectionTriggerMode
    // redux/shortcuts/shortcuts.clear_topic
    'shortcut.chat.clear': Record<string, unknown>
    // redux/shortcuts/shortcuts.copy_last_message
    'shortcut.chat.copy_last_message': Record<string, unknown>
    // redux/shortcuts/shortcuts.search_message_in_chat
    'shortcut.chat.search_message': Record<string, unknown>
    // redux/shortcuts/shortcuts.toggle_new_context
    'shortcut.chat.toggle_new_context': Record<string, unknown>
    // redux/shortcuts/shortcuts.exit_fullscreen
    'shortcut.exit_fullscreen': Record<string, unknown>
    // redux/shortcuts/shortcuts.search_message
    'shortcut.global.search_message': Record<string, unknown>
    // redux/shortcuts/shortcuts.show_app
    'shortcut.main_window.show': Record<string, unknown>
    // redux/shortcuts/shortcuts.mini_window
    'shortcut.mini_window.show': Record<string, unknown>
    // redux/shortcuts/shortcuts.show_settings
    'shortcut.show_settings': Record<string, unknown>
    // redux/shortcuts/shortcuts.toggle_show_assistants
    'shortcut.toggle_show_assistants': Record<string, unknown>
    // redux/shortcuts/shortcuts.new_topic
    'shortcut.topic.new': Record<string, unknown>
    // redux/shortcuts/shortcuts.zoom_in
    'shortcut.zoom_in': Record<string, unknown>
    // redux/shortcuts/shortcuts.zoom_out
    'shortcut.zoom_out': Record<string, unknown>
    // redux/shortcuts/shortcuts.zoom_reset
    'shortcut.zoom_reset': Record<string, unknown>
    // redux/settings/enableTopicNaming
    'topic.naming.enabled': boolean
    // redux/settings/topicNamingPrompt
    'topic.naming.prompt': string
    // redux/settings/pinTopicsToTop
    'topic.pin_to_top': boolean
    // redux/settings/topicPosition
    'topic.position': string
    // redux/settings/showTopicTime
    'topic.show_time': boolean
    // redux/settings/assistantIconType
    'ui.assistant_icon_type': string
    // redux/settings/clickAssistantToShowTopic
    'ui.click_assistant_to_show_topic': boolean
    // redux/settings/customCss
    'ui.custom_css': string
    // redux/settings/navbarPosition
    'ui.navbar.position': string
  }
}

/* eslint sort-keys: ["error", "asc", {"caseSensitive": true, "natural": false}] */
export const DefaultPreferences: PreferencesType = {
  default: {
    'app.developer_mode.enabled': false,
    'app.disable_hardware_acceleration': false,
    'app.dist.auto_update.enabled': true,
    'app.dist.test_plan.channel': 'UpgradeChannel.LATEST',
    'app.dist.test_plan.enabled': false,
    'app.language': null,
    'app.launch_on_boot': false,
    'app.notification.assistant.enabled': false,
    'app.notification.backup.enabled': false,
    'app.notification.knowledge.enabled': false,
    'app.privacy.data_collection.enabled': false,
    'app.proxy.bypass_rules': null,
    'app.proxy.mode': 'system',
    'app.proxy.url': null,
    'app.spell_check.enabled': false,
    'app.spell_check.languages': [],
    'app.theme.mode': 'ThemeMode.system',
    'app.theme.user_defined': { colorPrimary: '#00b96b' },
    'app.theme.window_style': 'opaque',
    'app.tray.enabled': true,
    'app.tray.on_close': true,
    'app.tray.on_launch': false,
    'app.user.id': 'uuid()',
    'app.user.name': '',
    'app.zoom_factor': 1,
    'chat.code.collapsible': false,
    'chat.code.editor.autocompletion': true,
    'chat.code.editor.fold_gutter': false,
    'chat.code.editor.highlight_active_line': false,
    'chat.code.editor.keymap': false,
    'chat.code.editor.theme_dark': 'auto',
    'chat.code.editor.theme_light': 'auto',
    'chat.code.execution.enabled': false,
    'chat.code.execution.timeout_minutes': 1,
    'chat.code.image_tools': false,
    'chat.code.preview.theme_dark': 'auto',
    'chat.code.preview.theme_light': 'auto',
    'chat.code.show_line_numbers': false,
    'chat.code.viewer.theme_dark': 'auto',
    'chat.code.viewer.theme_light': 'auto',
    'chat.code.wrappable': false,
    'chat.input.backspace_delete_model': true,
    'chat.input.paste_long_text_as_file': false,
    'chat.input.paste_long_text_threshold': 1500,
    'chat.input.quick_panel.triggers_enabled': false,
    'chat.input.send_message_shortcut': 'Enter',
    'chat.input.show_estimated_tokens': false,
    'chat.input.translate.auto_translate_with_space': false,
    'chat.input.translate.show_confirm': true,
    'chat.message.font': 'system',
    'chat.message.font_size': 14,
    'chat.message.math_engine': 'KaTeX',
    'chat.message.multi_model.fold_display_mode': 'expanded',
    'chat.message.multi_model.grid_columns': 2,
    'chat.message.multi_model.grid_popover_trigger': 'click',
    'chat.message.multi_model.style': 'horizontal',
    'chat.message.navigation_mode': 'none',
    'chat.message.show_divider': true,
    'chat.message.show_prompt': true,
    'chat.message.show_tokens': true,
    'chat.message.style': 'plain',
    'chat.message.thought.auto_collapse': true,
    'chat.narrow_mode': false,
    'data.backup.general.skip_backup_file': false,
    'data.backup.local.auto_sync': false,
    'data.backup.local.dir': '',
    'data.backup.local.max_backups': 0,
    'data.backup.local.skip_backup_file': false,
    'data.backup.local.sync_interval': 0,
    'data.backup.nutstore.auto_sync': null,
    'data.backup.nutstore.path': null,
    'data.backup.nutstore.skip_backup_file': null,
    'data.backup.nutstore.sync_interval': null,
    'data.backup.nutstore.sync_state': null,
    'data.backup.nutstore.token': null,
    'data.backup.s3.access_key_id': '',
    'data.backup.s3.auto_sync': false,
    'data.backup.s3.bucket': '',
    'data.backup.s3.endpoint': '',
    'data.backup.s3.max_backups': 0,
    'data.backup.s3.region': '',
    'data.backup.s3.root': '',
    'data.backup.s3.secret_access_key': '',
    'data.backup.s3.skip_backup_file': false,
    'data.backup.s3.sync_interval': 0,
    'data.backup.webdav.auto_sync': false,
    'data.backup.webdav.disable_stream': false,
    'data.backup.webdav.host': '',
    'data.backup.webdav.max_backups': 0,
    'data.backup.webdav.pass': '',
    'data.backup.webdav.path': '/cherry-studio',
    'data.backup.webdav.skip_backup_file': false,
    'data.backup.webdav.sync_interval': 0,
    'data.backup.webdav.user': '',
    'data.export.markdown.exclude_citations': false,
    'data.export.markdown.force_dollar_math': false,
    'data.export.markdown.path': null,
    'data.export.markdown.show_model_name': false,
    'data.export.markdown.show_model_provider': false,
    'data.export.markdown.standardize_citations': false,
    'data.export.markdown.use_topic_naming_for_message_title': false,
    'data.export.menus.docx': true,
    'data.export.menus.image': true,
    'data.export.menus.joplin': true,
    'data.export.menus.markdown': true,
    'data.export.menus.markdown_reason': true,
    'data.export.menus.notion': true,
    'data.export.menus.obsidian': true,
    'data.export.menus.plain_text': true,
    'data.export.menus.siyuan': true,
    'data.export.menus.yuque': true,
    'data.integration.joplin.export_reasoning': false,
    'data.integration.joplin.token': '',
    'data.integration.joplin.url': '',
    'data.integration.notion.api_key': '',
    'data.integration.notion.database_id': '',
    'data.integration.notion.export_reasoning': false,
    'data.integration.notion.page_name_key': 'Name',
    'data.integration.obsidian.default_vault': null,
    'data.integration.siyuan.api_url': null,
    'data.integration.siyuan.box_id': null,
    'data.integration.siyuan.root_path': null,
    'data.integration.siyuan.token': null,
    'data.integration.yuque.repo_id': '',
    'data.integration.yuque.token': '',
    'data.integration.yuque.url': '',
    'feature.csaas.api_key': '`cs-sk-${uuid()}`',
    'feature.csaas.enabled': false,
    'feature.csaas.host': 'localhost',
    'feature.csaas.port': 23333,
    'feature.minapp.max_keep_alive': 3,
    'feature.minapp.open_link_external': false,
    'feature.minapp.show_opened_in_sidebar': true,
    'feature.quick_assistant.click_tray_to_show': false,
    'feature.quick_assistant.enabled': false,
    'feature.quick_assistant.read_clipboard_at_startup': true,
    'feature.selection.action_items': defaultActionItems,
    'feature.selection.action_window_opacity': 100,
    'feature.selection.auto_close': false,
    'feature.selection.auto_pin': false,
    'feature.selection.compact': false,
    'feature.selection.enabled': false,
    'feature.selection.filter_list': [],
    'feature.selection.filter_mode': 'default',
    'feature.selection.follow_toolbar': true,
    'feature.selection.remember_win_size': false,
    'feature.selection.trigger_mode': 'selected',
    'shortcut.chat.clear': { editable: true, enabled: true, key: ['CommandOrControl', 'L'], system: false },
    'shortcut.chat.copy_last_message': {
      editable: true,
      enabled: false,
      key: ['CommandOrControl', 'Shift', 'C'],
      system: false
    },
    'shortcut.chat.search_message': { editable: true, enabled: true, key: ['CommandOrControl', 'F'], system: false },
    'shortcut.chat.toggle_new_context': {
      editable: true,
      enabled: true,
      key: ['CommandOrControl', 'K'],
      system: false
    },
    'shortcut.exit_fullscreen': { editable: false, enabled: true, key: ['Escape'], system: true },
    'shortcut.global.search_message': {
      editable: true,
      enabled: true,
      key: ['CommandOrControl', 'Shift', 'F'],
      system: false
    },
    'shortcut.main_window.show': { editable: true, enabled: true, key: [], system: true },
    'shortcut.mini_window.show': { editable: true, enabled: false, key: ['CommandOrControl', 'E'], system: true },
    'shortcut.show_settings': { editable: false, enabled: true, key: ['CommandOrControl', ','], system: true },
    'shortcut.toggle_show_assistants': { editable: true, enabled: true, key: ['CommandOrControl', '['], system: false },
    'shortcut.topic.new': { editable: true, enabled: true, key: ['CommandOrControl', 'N'], system: false },
    'shortcut.zoom_in': { editable: false, enabled: true, key: ['CommandOrControl', '='], system: true },
    'shortcut.zoom_out': { editable: false, enabled: true, key: ['CommandOrControl', '-'], system: true },
    'shortcut.zoom_reset': { editable: false, enabled: true, key: ['CommandOrControl', '0'], system: true },
    'topic.naming.enabled': true,
    'topic.naming.prompt': '',
    'topic.pin_to_top': false,
    'topic.position': 'left',
    'topic.show_time': false,
    'ui.assistant_icon_type': 'emoji',
    'ui.click_assistant_to_show_topic': true,
    'ui.custom_css': '',
    'ui.navbar.position': 'top'
  }
}

// === AUTO-GENERATED CONTENT END ===

/**
 * 生成统计:
 * - 总配置项: 170
 * - electronStore项: 2
 * - redux项: 168
 * - localStorage项: 0
 */
